package sis2.pkg2020.modelo;
// Generated 05-abr-2020 15:22:34 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Trabajadorbbdd generated by hbm2java
 */
public class Trabajadorbbdd  implements java.io.Serializable {


     private Integer idTrabajador;
     private Categorias categorias;
     private Empresas empresas;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private String nifnie;
     private String email;
     private Date fechaAlta;
     private String codigoCuenta;
     private String iban;
     private Set nominas = new HashSet(0);
     
     /****NO PERSISTIDOS ****/
     private String prorrata;
     private String paisCCC;
     private String extra;


    public Trabajadorbbdd() {
    }

	
    public Trabajadorbbdd(Categorias categorias, Empresas empresas, String nombre, String apellido1, String nifnie) {
        this.categorias = categorias;
        this.empresas = empresas;
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.nifnie = nifnie;
    }
    public Trabajadorbbdd(Categorias categorias, Empresas empresas, String nombre, String apellido1, String apellido2, String nifnie, String email, Date fechaAlta, String codigoCuenta, String iban, Set nominas) {
       this.categorias = categorias;
       this.empresas = empresas;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.nifnie = nifnie;
       this.email = email;
       this.fechaAlta = fechaAlta;
       this.codigoCuenta = codigoCuenta;
       this.iban = iban;
       this.nominas = nominas;
    }

    /**
     * Constructor para copia profunda del objeto
     * @param trabajador 
     */
    Trabajadorbbdd(Trabajadorbbdd trabajador) {
           
        this.categorias = trabajador.getCategorias();
       this.empresas = trabajador.getEmpresas();
       this.nombre = trabajador.getNombre();
       this.apellido1 = trabajador.getApellido1();
       this.apellido2 = trabajador.getApellido2();
       this.nifnie = trabajador.getNifnie();
       this.email = trabajador.getEmail();
       this.fechaAlta = trabajador.getFechaAlta();
       this.codigoCuenta = trabajador.getCodigoCuenta();
       this.iban = trabajador.getIban();
       this.nominas = trabajador.getNominas();

    }
   
    
    public Integer getIdTrabajador() {
        return this.idTrabajador;
    }
    
    public void setIdTrabajador(Integer idTrabajador) {
        this.idTrabajador = idTrabajador;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public String getNifnie() {
        return this.nifnie;
    }
    
    public void setNifnie(String nifnie) {
        this.nifnie = nifnie;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public String getCodigoCuenta() {
        return this.codigoCuenta;
    }
    
    public void setCodigoCuenta(String codigoCuenta) {
        this.codigoCuenta = codigoCuenta;
    }
    public String getIban() {
        return this.iban;
    }
    
    public void setIban(String iban) {
        this.iban = iban;
    }
    public Set getNominas() {
        return this.nominas;
    }
    
    public void setNominas(Set nominas) {
        this.nominas = nominas;
    }


    
   

     @Override
    public String toString() {
        return nombre +  
                " " + apellido1 +  
                " " + apellido2 +  
                " " + nifnie +  
                " " + email +  
                "fechaAlta=" + fechaAlta +
                " codigoCuenta='" + codigoCuenta   +
                " iban='" + iban + 
                " Empresa=" + empresas.getNombre() +
                " Categoria=" + categorias.getNombreCategoria()+"\n\n" 
                ;
    }
    public String toStringHQL() {
        return "" +
               
                "Nombre='" + nombre + '\'' +
                ", apellidos" +apellido1 +" "+ apellido2 + '\'' +
                ", nifnie='" + nifnie + '\'' +
                ", Empresa=" + empresas.getNombre() +
                ", Categoria=" + categorias.getNombreCategoria() 
                ;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            //System.out.println("1--");
            return true;
        }
        if (obj == null) {
            //System.out.println("2--");
            return false;
        }
        if (getClass() != obj.getClass()) {
                //System.out.println("3--");
            return false;
        }
        final Trabajadorbbdd other = (Trabajadorbbdd) obj;
        if (!Objects.equals(this.nombre, other.nombre)) {
            //System.out.println("4--");
            return false;
        }
        if (!Objects.equals(this.apellido1, other.apellido1)) {
            //System.out.println("5--");
            return false;
        }
     
        if (!Objects.equals(this.nifnie, other.nifnie)) {
            //System.out.println("7--");
            return false;
        }
       
    
        return true;
    }

    public String getProrrata() {
        return prorrata;
    }

    public void setProrrata(String prorrata) {
        this.prorrata = prorrata;
    }


    public String getPaisCCC() {
        return paisCCC;
    }

    public void setPaisCCC(String paisCCC) {
        this.paisCCC = paisCCC;
    }

    public String getExtra() {
        return extra;
    }

    public void setExtra(String extra) {
        this.extra = extra;
    }
    
    public static ArrayList<Trabajadorbbdd> deepCopia(ArrayList<Trabajadorbbdd> trabajador) throws CloneNotSupportedException{
        
        ArrayList<Trabajadorbbdd> clon = new ArrayList<Trabajadorbbdd>(trabajador.size());
        for(Trabajadorbbdd item: trabajador){
            clon.add((Trabajadorbbdd) item.clone());
            
        }
         return clon;
    }  
    




}


